### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ZeiZeiii** [horse4lunch/highlight-stackable-items#2]
Add tap for opt-out notifications. Currently if notifications are on in 'Ground items', it will send notifications on stackables as well. Id like to opt-out from this.

**Comment by horse4lunch** [comment]
Unfortunately there would be no way for me to do this without altering the actual Ground items plugin. Someone had already tried adding the Highlight stackables function to the Ground items plugin and it never got merged. Which is why i made this a plugin rather than editing Ground items plugin.
